name: CICD-HTTPS-SETUP

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/CICD-HTTPS-SETUP.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_REMOTE_HOST }}
          username: ${{ secrets.AWS_REMOTE_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          source: "."
          target: "~/app"

      - name: SSH & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_REMOTE_HOST }}
          username: ${{ secrets.AWS_REMOTE_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            cd ./angular/sample-app/deployment
            bash deploy.sh