name: Angular App to Remote AWS-EC2 Remote Docker Host

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'angular/sample-app/**'
      - '.github/workflows/CICD-Angular-AWS.yml'                      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        ssh-keyscan -H ${{ secrets.AWS_REMOTE_HOST }} >> ~/.ssh/known_hosts

    - name: Build Docker image
      run: docker build -t angular-app ./angular/sample-app

    - name: Save Docker image to tar
      run: docker save angular-app -o angular-app.tar

    - name: Copy image to remote server
      run: scp angular-app.tar ${{ secrets.AWS_REMOTE_USER }}@${{ secrets.AWS_REMOTE_HOST }}:/tmp/

    - name: Load image & run on remote server
      run: |
        ssh ${{ secrets.AWS_REMOTE_USER }}@${{ secrets.AWS_REMOTE_HOST }} << 'EOF'
          docker load -i /tmp/angular-app.tar
          docker stop angular-app || true && docker rm angular-app || true
          docker run -d --name angular-app -p 4200:80 angular-app
        EOF
